LITE-19565: Add license for non-opensource options
cloudblue/connect-extension-python-boilerplate pull request #11
Opened 2021-07-19 12:59 UTC by jpdolz

2021-07-19 13:01 UTC, marcserrat requested changes

2021-07-19 13:01 UTC, marcserrat commented on cookiecutter.json
> +        "Other, not Open-source"
NO, we can't......

We only can support open-source licensed extensions to run on our cloud....

2021-07-22 12:45 UTC, marcserrat approved these changes

2021-07-22 14:04 UTC, ffaraoneim approved these changes

2021-07-22 14:26 UTC, merged